### ISSUE TITLE
Purpose of generators in "AbstractClassWithMethods" class

### ISSUE THREAD

**Issue by aik099** [goaop/parser-reflection#14]
The `AbstractClassWithMethods` class used in `ReflectionMethodTest` test contains 2 generators, but test itself doesn't call them. Are they really needed in there?

If the propose is to see if PHP parser can parse them correctly, then we should be believing it can by default.

**Comment by lisachenko** [comment]
Test itself uses such methods indirectly for correct detection of generators via [`ReflectionMethod->isGenerator()`](http://php.net/manual/en/reflectionfunctionabstract.isgenerator.php).

So, if we look at method body and can see T_YIELD token, this doesn't mean that function is generator, because it can be a nested closure with generator.

**Comment by aik099** [comment]
While working on a PR for #13 it's the only place that causes tests to fail on PHP 5.4 now.

Any idea how this can be properly handled? Maybe class can be copy-pasted and in copied version generator code removed. Then depending on PHP version include one file or another?

**Comment by lisachenko** [comment]
I think that only available solution for you is to create a fork and then maintain it for PHP5.4 and ask a time for moving to the newest version of PHP.
