### ISSUE TITLE
Support for finding traits and interfaces in ReflectionFileNamespace.

### ISSUE THREAD

**Issue by onet4** [goaop/parser-reflection#63]
How hard would it be to support methods to find defined traits and interfaces for the `ReflectionFileNamespace` class?

```
    public function getTrait($traitName) {}
    public function getTraits() {}
    public function getInterface($interfaceName) {}
    public function getInterfaces() {}
```

**Comment by lisachenko** [comment]
Hi! I think that you don't need this API, because PHP has only one `ReflectionClass` class for classes, traits and interfaces. 

You could check for trait or interface with the help of `ReflectionClass->isTrait()` or `ReflectionClass->isInterface()`. So just use `array_filter` or `foreach` to filter traits or interfaces from the file namespace.

**Comment by onet4** [comment]
Okay.
